#lang scheme
(define (mul a b)
  (define (double x) (* x 2))
  (define (halve x)
    (if (= (remainder x 2) 0)
        (/ x 2)
        (error "err: the x of (halve x) must be an even.")))
  (define (even? x) (= (remainder x 2) 0))
  (define (mul-aux a b n)
    (cond ((= b 0) n)
          ((even? b) (mul-aux (double a) (halve b) n))
          (else (mul-aux a (- b 1) (+ n a)))))
  (if (< a b)
      (mul-aux b a 0)
      (mul-aux a b 0)))